import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/providers/modal-provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ahads CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorText: "#000",
          colorPrimary: "#0E78F9",
          colorBackground: "#fff",
          colorInputBackground: "#fff",
          colorInputText: "#000",
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          {children}
          <ModalProvider />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
